### ISSUE TITLE
Недостатки проекта

### ISSUE THREAD

**Issue by DenZhid** [DenZhid/2022-automated-testing#11]
~~1. Не используем паттерны Page element/Декоратор/ Wrapper (что-то из этого должны активно использоваться);~~
~~2. Нужен хотя бы один из следующих паттернов:
    Data provider
    Factory
    Singleton
    Builder
    Strategy~~
3. Не используется (должно активно использоваться всё):
    assertAll()
    Запуск тестов по пакетам/классам
    ~~Таймауты для тестов~~
   ~~@Tag/@Disabled/@DisplayName~~

**Comment by zadorotskas** [comment]
Добавил паттерн Factory
