### ISSUE TITLE
Проверка проекта

### ISSUE THREAD

**Issue by Sanerins** [DenZhid/2022-automated-testing#14]
### Что понравилось:

1. Очень много разнообразных и интересных тестов
2. Очень много комментариев, поясняющих логику работы тестов, что хорошо сказывается на читаемости кода
3. Много коммитов, указывающих на работу с `GitFlow` и даже работа с `issues`, что очень похвально
4. Использовано большое количество разных паттернов, код интересный и многообразный

### К чему возникли замечания:

1. Не понравилось, что `login` и `password` - это просто `final` константа в файле `parentTest` - мне кажется, что такое очень неудобно - легко закоммитить по ошибке при добавлении изменений в `git`, и слить важную инфу. Возможно стоило вынести эту информацию в отдельный файл `.txt`, добавить его в `.gitignore`, либо использовать такую крутую штуку, как `environment variables`
2. Не поняли, зачем `WebDriver` вынесен в отдельную папку и подключается явно - селенид и сам умеет запускать нужную версию веб драйвера для конкретного компьютера, еще и с учетом операционной системы. У меня, например, Linux, поэтому `.exe` драйвер, естественно, сломался, и технически все тесты завершились ошибкой, однако банальное удаление `System.setProperty()` в `createWebDriver` решило эту проблему и все стало работать как надо, так как селенид выбрал драйвер сам
3. Не особо понравился нейминг `ParentTest`: как нам показалось - звучит больше как имя одного из классов-тестов, а не базовый класс, от которого все наследуются, более того - учитывая что класс - база для остальных классов, а не самостоятельный тест, так и напрашивается сделать его абстрактным
4. Возможно использование родительского конструктора для передачи текста ошибки - это очень необычное поведение для оного, скорее всего человек, который в первый раз видит, может запутаться. Возможно можно было бы создать однострочный абстрактный метод по типу `getErrorMessage` в классе Page, который будет возвращать строчку текста ошибки, и его надо будет обязательно переопределить в классе - наследнике.
5. Мне кажется, что `suite` со всеми тестами лучше было бы сделать с использованием аннотоции `@SelectPackages("tests")` (только надо будет перенести `AllTests` в другой пакет перед этим). Тогда не будет проблемы, что при создании нового теста надо будет не забыть добавить его в `suite`
6. Возможно использование матчеров было немножко маловато: лишь в двух местах в одном файле, но цели использовать их везде и не стояло, поэтому наверное норм
7. В `MusicPage` в методе `getPlayButton` можно было бы обойтись одной строчкой использовав тернарный оператор, еще бы и `Java` оптимизировала бы это)
8. Как маленькая придирка - есть неиспользованный `import` в `MusicTest` :)

### Итоги

Как нам показалось - работа очень достойная и сразу видно, что было вложено много сил и работы. Придирки, озвученные выше, не критичны, порой зависят от вкуса и стиля, и все их можно очень легко исправить за пол часа.
С другой стороны тестов много, они очень необычны и сложны, но при этом работают
По сему мы решили поставить финальную оценку в виде очень крепких и достойных
### Проверяли:
Косницкий Александр
Победоносцев Кирилл
Щередин Артем

**Comment by blaackpanter** [comment]
Структура у ревью хорошая. Правильно, что написали, что понравилось в проекте. Подметили достаточно много моментов в работе, но все же их гораздо больше, некоторые лежат довольно глубоко :) Советую ознакомиться с моим ревью для более четкого понимания.

**Comment by DenZhid** [comment]
Solved
