### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by blaackpanter** [DenZhid/2022-automated-testing#16]
Основная мысль по поводу тестов. Сейчас тесты довольны маленькие, которые практически не содержат @Before и @After, логика довольно простая, поэтому можно позволить несколько @Test в одном классе. Это не является ошибкой, но все же хочется видеть формат "Один тест - один класс" с грамотным названием (сразу должно быть понятно,  что проверяется в тесте).

Не очень понятно, зачем отдельный тест на это и какую нагрузку смысловую он несет. Это можно вынести в часть другого теста. 
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/tests/GroupTest.java#L34

Про логику в тестах (!).
Нам нужно всегда сделать какое-то действие в тесте, а затем проверить, что так произошло. Если не произошло, значит вывести информацию об этом. Здесь нужно тем самым участником, например, залогиниться, вступить в группу, а потом другим юзером или тем же проверить, что в участниках группы он отображается. Иначе зачем мы это проверяем. Такое есть во многих тестах, это надо доработать на примере этого. 
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/tests/GroupTest.java#L42

Это можно вынести в @After данного теста.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/tests/MusicTest.java#L62

Здесь и дальше в assert можно добавить комментарий в случае падения.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/tests/MusicTest.java#L61

После завершения теста нужно оставаться в браузере, чтобы выполнить все нужные зачистки. Работу с урлом надо убрать.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/tests/PhotoTest.java#L77

Надо переименовать в LoginPage, такое название можно принять за класс, который отвечает за работу с логами.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/LogPage.java#L10

Я бы переименовала в BasePage. Не нужно сокращать, лучше назвать так, чтобы сразу было понятно, что там.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/Page.java#L10

На странице может быть порядка десяти элементов, которые нужно проверить, чтобы сказать "страница загрузилась". Не думаю, что это будет удобно все передавать. Это первый момент.
Второй момент. С таким подходом мы не узнаем, какой именно элемент не был найден. Мы всегда будем получать сообщение "Log page init error". Это потом добавит нам лишнее время поиска устаревшего локатора, например. Нужно переписать. 
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/LogPage.java#L16

Таким действием мы можем пропустить баг, вдруг в какой-то момент кнопка "Войти" пропала. Нужно найти кнопку входа и нажать ее. 
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/LogPage.java#L21

Формат перехода по страницам через урл здесь не подходит. Нужно ходить по тулбарам/боковым панелям, чтобы попасть туда, куда нужно. 
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/GroupPage.java#L53

Хорошая возможность написать обертку (wrapper) и получать нужный элемент.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/EditAlbumPage.java#L36

Либо обертку, либо вынести в переменную.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/MembersGroupPage.java#L28

Чтобы не кидать ошибку, здесь можно через ассерт сделать.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/MembersGroupPage.java#L25

Зачем в одном классе три класса? Вынести. Потом можно объединить в директорию music.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/MusicPage.java#L52

Написала выше.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/PhotoPage.java#L73

Выше писала про аналогичное.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/UserGroupsPage.java#L18

Тут должны быть проверены все элементы страницы в методе check(), чтобы сказать, что страница загружена. Класс с тулбаром вынести, работу с List убрать.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/MainPage.java#L21

По урлам не ходим, заходим в списке групп (или ищем в поиске), делаем обертку над результатом найденным, берем группу по имени или любому другому параметру.
https://github.com/DenZhid/2022-automated-testing/blob/97aa21eb9675662f7f3112cbe81481d431f05595/src/test/java/pages/GroupPage.java#L25

**Comment by blaackpanter** [comment]
Ревью получилось большим, но хочется отметить, что работа хорошая. Вы много реализовали, нужно доработать. Возможно, доосмыслить некоторые моменты.

**Comment by DenZhid** [comment]
Всё исправлено!)
