### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by blaackpanter** [DenZhid/2022-automated-testing#4]
1 TestLogPage
Проверка в тесте должна быть через assert.

**Относится ко всем пейджам.**
1 Переменные (локаторы) пишем  через By.xpath() или By.id()
2 Метод isPresent() сделать void и лучше бы переименовать в check(), так будет понятнее. 
3 В будущем методе check(), который нужен нам для проверки видимости/нахождения на странице элемента и тд для дальнейшей работы с ним (клик, например), мы делаем следующее:
с помощью assert и ExpectedConditions проверяем присутствие элемента на странице, также не забываем про ожидания (это для селениума).Нужное применить для селенида. Например,
webDriver.findElement(By.id(EMAIL_FIELD_ID)).isDisplayed().
4 Все вынести в переменные, никакого хардкора.
5. sleep() быть не должно.

**Comment by DenZhid** [comment]
Все замечания учтены и исправлены
